package org.mlc.shoppingcart.model

import jakarta.persistence.*
import java.math.BigDecimal
import java.math.RoundingMode

/**
 * Represents a shopping cart in the e-commerce system.
 * A cart holds a collection of [CartItem]s and maintains a calculated total amount.
 * It is uniquely associated with a [User].
 */
@Entity
class Cart(
    /**
     * The unique identifier for the shopping cart.
     * It's auto-generated by the database upon creation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long = 0L,

    /**
     * The total monetary amount of all items currently in the cart.
     * This field is calculated and updated whenever cart items are added, removed, or quantities change.
     * Stored with 10 digits of precision and 2 decimal places for accurate financial calculations.
     */
    @Column(name = "total_amount", precision = 10, scale = 2)
    var totalAmount: BigDecimal = BigDecimal.ZERO,

    /**
     * The [User] to whom this cart belongs. This is a one-to-one relationship.
     * `@JoinColumn(name = "user_id")` specifies the foreign key column in the carts table.
     */
    @OneToOne
    @JoinColumn(name = "user_id")
    val user: User,

    /**
     * A mutable set of [CartItem]s belonging to this cart.
     * This is a one-to-many relationship, meaning one cart can have multiple items.
     *
     * - `mappedBy = "cart"`: Indicates that the `cart` field in the [CartItem] entity
     * is the owning side of this bidirectional relationship and is responsible for managing the foreign key.
     * - `cascade = [CascadeType.ALL]`: Ensures that operations like saving or deleting a cart
     * will also affect its associated items.
     * - `orphanRemoval = true`: Ensures that if a CartItem is removed from this set,
     * it's also deleted from the database, as it cannot exist without its parent cart.
     * - `fetch = FetchType.EAGER`: Specifies that the collection of [CartItem]s should be loaded
     * immediately with the cart. This is often suitable for carts as their items are usually needed.
     */
    @OneToMany(mappedBy = "cart", cascade = [CascadeType.ALL], orphanRemoval = true, fetch = FetchType.EAGER)
    var cartItems: MutableSet<CartItem> = mutableSetOf(),
)

/**
 * Extension function for [Cart] to update its [totalAmount].
 * This recalculates the sum of all [CartItem.totalPrice]s within the cart
 * and applies rounding to ensure exactly two decimal places, essential for financial accuracy.
 * This function should be called whenever the contents of the cart (items, quantities) change.
 */
fun Cart.updateOverallTotalAmount() {
    totalAmount = cartItems.sumOf { it.totalPrice }
        .setScale(2, RoundingMode.HALF_UP)
}